// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJfM7EKNoKaJl5e6OSJMD56Zi7ms0BppA',
    appId: '1:511586292086:web:492844e3b8967f5780ea57',
    messagingSenderId: '511586292086',
    projectId: 'heco-color-help',
    authDomain: 'heco-color-help.firebaseapp.com',
    storageBucket: 'heco-color-help.firebasestorage.app',
    measurementId: 'G-NL62EVM5VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIvxI_QVLV6Ib7QuI2gKQgHCJFkGsoL9A',
    appId: '1:511586292086:android:26a5611d25c4e1dd80ea57',
    messagingSenderId: '511586292086',
    projectId: 'heco-color-help',
    storageBucket: 'heco-color-help.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2KTbbjNjN-oVRAzpsSf9a_ZgE1wSJrdg',
    appId: '1:511586292086:ios:43ec5d983bdba91f80ea57',
    messagingSenderId: '511586292086',
    projectId: 'heco-color-help',
    storageBucket: 'heco-color-help.firebasestorage.app',
    iosBundleId: 'com.example.heco',
  );
}
